## Spring configuration
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

## Server
server:
  port: 8700

## Logging
logging:
  level:
    org:
      explorer: debug

## Ethereum
## TODO :: add websocket after web3j release
eth:
  nodes:
  - nodeName: parity-1
    rpc:
      type: websocket
      url: http://192.168.5.77:8450/
    block:
      time: 15000
    subscribe:
      block: true
